# Generated by Django 5.2.4 on 2025-09-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='authors',
        ),
    ]
