# Generated by Django 5.2.4 on 2025-09-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_author_profile_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='authors',
            new_name='author',
        ),
    ]
